image: archlinux
repositories:
  sr.ht: https://mirror.sr.ht/archlinux/sr.ht/#1ED4E14494433AE3FD302CAB74B4BCCEA60D0437
packages:
  - sassc
  - python-setuptools
  - python-srht
  - python-pgpy
  - python-celery
  - python-redis
  - python-yaml
  - python-markdown
  - python-bleach
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
  - https://git.sr.ht/~sircmpwn/sr.ht-pkgbuilds
environment:
  project: builds.sr.ht
  repo_server: deploy@mirror.sr.ht
  repo_path: /var/html/mirror/sr.ht/archlinux
  master: deploy@builds.sr.ht
  slaves:
    - deploy@yui.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018 # ssh deploy key
  - 3e65a1a8-a20f-4f6b-a452-df2ac398bc1e # package signing key
tasks:
  - build: |
      cd ${project}
      ./setup.py build
  - archive: |
      cd ${project}
      pkgver=$(git describe | sed -e 's/-/_/g')
      echo "pkgver=$pkgver" >> ~/.buildenv
      git archive -o ~/sr.ht-pkgbuilds/${project}/${project}-$pkgver.tar.xz \
        --prefix=${project}-$pkgver/ HEAD
  - package: |
      cd sr.ht-pkgbuilds/${project}
      prev_pkgver=$(pacman -Si ${project} | grep Version | cut -d ':' -f2 | cut -d ' ' -f2)
      prev_pkgrel=$(printf "%s" "$prev_pkgver" | cut -d'-' -f2)
      prev_pkgver=$(printf "%s" "$prev_pkgver" | cut -d'-' -f1)
      if [ "$prev_pkgver" == "$pkgver" ]
      then
        pkgrel=$(expr $prev_pkgrel + 1)
      else
        pkgrel=1
      fi
      sed -e "s/pkgver=.*/pkgver=$pkgver/" -i PKGBUILD
      sed -e "s/pkgrel=.*/pkgrel=$pkgrel/" -i PKGBUILD
      echo "pkgrel=$pkgrel" >> ~/.buildenv
      updpkgsums
      makepkg --config ../makepkg.conf -s --noconfirm
      cd ~/${project}
      git describe --exact-match HEAD || complete-build
  - deploy: |
      cd sr.ht-pkgbuilds/${project}
      sshopts="-o StrictHostKeyChecking=no"
      rsync --rsh="ssh $sshopts" -rP *.pkg.tar.xz{,.sig} $repo_server:$repo_path/
      ssh $sshopts $repo_server repo-add -n -R \
        $repo_path/sr.ht.db.tar.gz \
        $repo_path/${project}-$pkgver-$pkgrel-any.pkg.tar.xz
      ssh $sshopts $repo_server repo-add -n -R \
        $repo_path/sr.ht.db.tar.gz \
        $repo_path/${project}-images-$pkgver-$pkgrel-any.pkg.tar.xz
      ssh $sshopts $master sudo /usr/local/bin/update-srht ${project}
      for server in "${slaves[@]}"
      do
        ssh $sshopts $server sudo /usr/local/bin/update-srht ${project} ${project}-images
      done
