image: archlinux
repositories:
  sr.ht: https://mirror.sr.ht/sr.ht/archlinux/#1ED4E14494433AE3FD302CAB74B4BCCEA60D0437
packages:
  - sassc
  - python-setuptools
  - python-srht
  - python-pgpy
  - python-celery
  - python-redis
  - python-yaml
  - python-markdown
  - python-bleach
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
  - https://git.sr.ht/~sircmpwn/sr.ht-pkgbuilds
environment:
  repo_server: deploy@mirror.sr.ht
  repo_path: /var/html/mirror/sr.ht/archlinux
  master: deploy@builds.sr.ht
  slaves:
    - deploy@yui.runners.sr.ht
tasks:
  - keys: |
      -----BEGIN PGP MESSAGE-----

      hQEMAwDxEZj45VMLAQf6AkYRTzP8vfAAJDucsg2IvIzTmSMfH+m/iJusX0QmhK0w
      OcMV/DNCDWgXQi18/mE/RFjJtwGnxs7YIjt4Pjny3biT8mHrjUli8G1N8Yhc/yQz
      heP6N0oNHrNSkDIfRXteoU6BxP1nNIyVA2pXHxb83CRta55KMJ05IT/r4g11cymy
      TN0uU+AGft+Tfm3zMJKPc7ZAVI/Ooi4QT4wvUSjn5TCT/onIVMkTqf3AEkR9b03u
      N2H9tKwVuWpAIG/Z7WEHiv3RM/O4wuoKO/0R+JafjIq0ihe5+MvM+Sy3D7jAWF0w
      mxA2ZNs7qB/pqR+1cLndx4NDfw/chZTAqbEfslsle9LrAWywGr+ks+dOC2oQVonH
      /ECAvZnBmFA3dkoX1yiPM1bR6OpBSPpaWKBCvNYCwdZ/P4iR+BUVuz9OPQwN541M
      j97uKCzm8h7pLL2xOzLEHrDUSuyRBq/03T9zsqdlzYBvGi5X+Z0hEKQeUTQvPRG4
      akDYGY/WYNOYST86NIAC+ckWJU7ipl+Yjl472G7SLEZPHT5yQR+kPNhjOs0CJKX1
      Sz3c9iWV+15RhDHA+fjPxCb1PWFLnUhVkGu5YhUVcq9bHiEtiEGBmgmirNuCOQ6U
      t/pH4kYXduWmPi2dg87zjRgx/DIJ7bPujk/GGI01YEB0Axst7RLHKFfuG/UjBZxz
      hsotbh8gkr6vPmEtogpPWZjWhV3W5TYSIlaz7jabLbwtyT3EurMD3AwESW5lSflp
      P/+tapuXYR1yfkIwmRpfydbGxVccHDiSyNhCyXkTminf7Rs3gHdugIMW5qymk7Od
      XYndR3+3AUf/MvvVfm4pgoMn2BxW/TPK1zn0MLy1itYVWtzHmwd86Vy//MupCjdl
      I6eiZiakGzjK7tT1FPl4ar8QOkT5PVqgL0ZG2OoYrLnWzC7E2qpeidz8lMBUQPvy
      zdrzPza9N0XX0PVxnpWCcJfGUigRLIBzjgMBNsvflmsTK2v7HljOlFkPDZlLu4Xj
      zpiNip+q2b0HmvdEYB0cCeBNNP/UtFmDKTeW++ADKXBss7RC94F2GGOO9rBUL4pw
      vktKHIwYOENnv8EDoVHfYiyfZHu2fhiuFPP9C5OGTX4tbIoVTgQNlKfq4Uz+M/io
      fAmKL+quVUahDyv+IBx5A9L9Dw375vbfXS+14J1XehpVc1K/89amNHqUJl+h4m1h
      O7wlGbTOroUDAjB6zahPnSd7SIAPT27JmjV422BHn5R3fUYbpU9cTgFDdqVMzdF7
      MY1zszXXUeLCSzzRC/z4Am2K8LMmHK7reGXp8tBS7Q4NgL6Nu3R397F8UXebij08
      fCTBzPl9Xe7/NdxKp/f6assaT+CaG/GB4niOoMlwWhVgECrWjF9RBoxLEqvEEpiJ
      /+elMhCt5EGICslo5ayl4qmgOl4AaTJJEaxVIlG9RK68nQwxm6Ax+D01lDPqcPw2
      t98Ug4ate1/v0t3SCCp9jxbc20bsQbRNh6GXbZwIBdeqYPeMm7pmGqPnGpbYrOBu
      W0cQAr/FM/fB7cnuGQXtyjkxQ6sgAlIHNCBjnM7jlqn6yWky5HJpn3oXdUZJF/LU
      MQTd6f67IOwZb7/a/e+UhWyaFYeb1bMoYnNJITAl+amKb/h+V+14Mt5qLsa4ynLx
      6Ow/YzrloOaR5U7UOGvzSqlAePrrmLkDpHF+V2w9RtDB8mI8glYOgwASYMoCvPfb
      Ke3ABe49P5euFTkdUNnEbPKjtu65Qt5XAzCjyo9VJ12rYCxundsyT1V4UQI/N7oI
      ccgNGLp3dENemSsO+cy/6PzCCdAMCd/6ODZkYaqPfVPwelDfQ/r1qrysw+j25+Of
      4u0S/aGPOviSM1Rn0MH7jvhA+izMjvWz37WQp8V5PycjkOoP6olNC+nETrjgfdop
      EWeZKCdwobGnPluBI+gOm2stuOkMHuYSO6SfTciLKOmvN5BY9m/aQv7doTWLNd8v
      QDoSz83BjX/DjIfgLwRsmu+ysRLcj7mL1dAdlNklmMOBMX3C12eiqCejpN5tiaML
      sxi23l/3M0nA1NsRYe0nvroUS13WEwQpUJsupRup/L9QLVrJnkMg20XHxjJMW7pp
      5NZy3ErPrEGjKDU8hKC83q3tk80YNGFj13gUGp4dMeaR+4qU/Ek98QYurYAiVJfk
      TojAzamkkbLn+sg3ZWdnEVnD7CdIgdRgYtQsIEeYiK5F2tbxPAcL8GW6k1Ds6qmo
      VG8K/WlB5bID6ZLYWCAdSMWLKCa0rcjXnoT9Pjzat7ObTLPiSlovPvCeVcYFfRUs
      ouvHVW3N6/z0eze4+AQp64IAl+48Wgt2aC1X+KK34G/KzVemcOCztzGMp153WfcG
      ij3utUXHzXvPVMnD/Su8L8kvTepLPr3YZWQssQ4avaeScOH8cvvr7SY6uV6yngf2
      FF+7PDuQz3OXR7pqIJ6nfB4kSSOHDebQHRS0kkOCyAst6UxWw9W7xpb8aMdpZTqS
      FzL3+/NxU4Iy7hX1W1tGWMZ2En5LMeRgTD2FkNt/ge+cZp9Ix422JcVuA1XJm3+p
      BiMzyGanRdKzCV7z4s1F3eoiAv2lcHrDZtOuPF+9Y3qKHyCPpyEFul1q7m8IQYJy
      hJTDClO5cunZH0XoyfNPFgTyirlaimuFiCZ9LUjc3q+BgiW39W0KQUrFrSBK9mOQ
      fu7zhSTSphRJltwJSmHIomP3F2OMsDnFuE8XX4pPWVY8f5QtYovavFvDSmwQhLqy
      GLJbdZyT/4CqJffyF4gpWj3nJnhtWZsDo5SvD5FmQ3iIjcz5Io0CeHIMRodbzF7X
      YkvPq51AP3kqAlNUezMZB14YLKrz09o0UzIIWj0CkIASKaM66sLIqRhc0Mcqnb8j
      qfN/Np3ZQXRVPsRv3jER5KMDqS7A0Q69e1WXSmUU2PfOaLAowY/C+3om6D3dtZHZ
      1DlZ/EmIhtilIVYrYoaVDB1q91ezjj7bqDu7mScyZYEUJFKGSxVulzeu5c52MN7X
      cn3png1FR/a6ybJ0t1ocBxOX7bGRc/EshEckkUHOUFQD/gOBOr1nEsnXnZFnHMvC
      JEAPJ1Zo5xGP+YyRxicQUzPq6rcDe0n5z/IoxceAcSRjYGxOIyno2vXUzSyCyWEP
      74hZ0icm5ori0V1A3ZCxONA/55MjBNfKenBRaNO2G+9nO1m3BTLjamGZiVYTz7oH
      GBHWjIia/2uLJVxlunYeuHhpTRZ7XCy2xWKJbHQ12nrBsv0cAPY+wBgwxJSYzqrG
      3vYrXupPG1uPt2niEV10jXPEeozcyBAUolab5mJGk8bEwDcQmtLTa10P2nzsbnP1
      IZfGNKLcXgqblegYYLm8DGYS1LQ9BIMtrFd6LVETImqu6THAOan5gjGGV/2JkPNj
      Mbc6QElTkI3HhCe/S76jP/s/MF1kpeswyO/0SVozk+0ir4vmTmfqcUmyWjWSMgZl
      VElF1A4HeHDYEDAgP2z0vjqsqjPW6vPYdbFlRgxalif2eDzXAvFB9AWBu7HawnnT
      IqKxQcAJ0pbmf4khpQVjNiPOR2CW7ym1Cx51pnT92NWpNVyS6uCSv+fHsymDoZUZ
      8/hhjA+ZSp6LobJQkHufG0UJVGZVVozWdHxGfLWH5R0yyLLbTwYutDspDA515qkJ
      t9Jyk55Nhmqyi3SFSamz5J3EZgSVGVYdA7Uu8Lpu/FC3VwYtd+H36XmHg1F3/mRR
      ceOtqslAAOKPjeBLf3Bj06sUwe/MjcvKqyZmfAs+EzGfnxymDI8h6/qlRpiuqaeU
      Bvb902rr7pqLWhJl1zaIFof6G++aDF9MBpL2mAkXTpE3HjzPvMFMzgF2rXUD6zFu
      UTf7BmIVTE0lxab3BE9UUsJ7uDZps8veBbGQ+Gw+LHge1Md59SSxa5VSwyodLzHz
      znjH0Z97YgXtVGBUBO/SCGTv8MT2zE+mqSSHm8aRiqOTzzfyaJEcTX2adSoMBsBv
      L3+FF6Lbhlo/dJUSMFq/4t/3Ss/c9ccbVqBAAREG+ybDJTscA2XHz8S7tjaPL4VE
      cmd4G5+rNEOsBCMXQtXORfVyOPT4cOhv17j9uQ2SDezlM5xdfxOKSryDfYGsqcmJ
      pQvDD8mNSPkNlasL72pszkJxKoKlW3MF6o7pDGtZdN2VPFUR+uW6iv3A/2VL+v4Y
      pk2L+ESM5554NOWuCAMDF2fBEP7Ce/G54ZlMcdH5eb22GI0aMo/iaSZCVxhZuUDg
      bBvmxwKYHEWDxJ8m2Jo9J3aBr+Ya1EEfi2PVNKILQCaSBqO6NoVCfQPQB6DpWoqg
      zz42nnX0FsnROHz40rJzLHE2Ut69GF9PQJg798UUCRh/NTPql6C/ouF64xspMlWv
      fPkxfMxmLuLTVRmt5G5NwDf0D06mUG9BwAEAKyPLKGlYbdz4C8bviiG8esUuxX4j
      gSVeACCEsR/4SxCzMo4jLPqDM6pdH9TS//YymCOQ8adlfOnd35ABPdCUs+eccN1C
      UD5Jy/CNavHc5izxvrQdU4nuiGlNYtnf1v3Zg3/0jNft7xwWOCJiGxhzl4ZbxDdo
      Vy3ehqIhMlOa3AzTKDVvjJUseBW3Tp5V9WcPCnvE5JFsEoH8Ep518ZRTyDT+eOpW
      OmFbX9tI/NYb5X65S7ozDAHdLnMDiaZWdYYhVZGpLn0Qa8LOG/b5KtXHqkLkV+pW
      ccnZuLAohYCfRcKcWNZTqX+0OcSjQtNup3rhgPXhWt5yxRDhCzs8E/zWe1lr6cDP
      lgU8v3soxhbsyrxhnNpVbONPREizGa5FK9trkXAWMJNrn/ItT9ePo3wyvWy3olPJ
      siRUrz5xhFJCi5JGW4mL9BHJm9MhxWR3RvXeSNXnvSPLDbk7tIVuhbeqJ9FDTFGO
      o6yvQBP6inmWPyBAToqsV/8CyW80c1lCt9fJXwWjoKpO7D5l+TM0teMth9xiDA5L
      dItEEsnWc0UZxl6V/Mlyptf2a5x2aeQ06UxW2bdOrOMbZA+zzGFD59ef+KTDgGWP
      zoNk01yDwR38h8dvtyt4H3sSeUqqUr+bhh5iBgLy60EPVjHEqXX4bIs9PaCHKi8P
      Q3k0kDLKVuQ2qyyILNkVUYkpIc+ICQ4CUKAOILDof7qRYHlh0UYkXdNMGrV75ckW
      +MZPy8SJu2J8e+Ozx/EDyDr9l8DsW1JrQQCce1IgMXE1PBs6UQpVHi4e80RrVw/G
      l3wEvcNX1sCoV/ezxnDzJYmsovB6GyOjMTY31JsJgPu3ROPfJuUsA0uM1LFuv/rv
      GHofdKG9qQM0yiPYFGpH7HeNJ8qhFHkdewma6l3bH1p5YxaHbU+XnlYdadwbSXVE
      s51pcPq82OnOTT6YWThYe80IObSZ1Au9T/rHBSYLaTTTVaVP02V6YBHby74jpKcB
      FpElnj+367vKwimseyVLGSpPXsne5qHwyoHXqC6uUZ1aHs75M6Dy6n/ZM/Y2yGih
      cKJxCt5q52Lvnci7nKFyQfe/tZjK3BPxMGbW9ISL6X0nYB550El/d3eW5p5PFSZk
      lVGpD34m8p6h1Sa6pr81oTj8JHVcCYG0sGnBsUfTGQUZcTe+ywOdN4K6q3PqYk7+
      mu+Y251UwBz/anUIUiwlY7JcmLmyikblZbR/LWbcHEXt0D+TWlvmECkdnyV5VGqp
      B34dijjxV/NQbY+2RfxwqoKyDLbEi0QNA+NVZ4BgaB2QTwO2ta8aJriJF3nH/A0A
      TLxsI1WCW1uhME2LotG8jt0=
      =HjpK
      -----END PGP MESSAGE-----
  - build: |
      cd builds.sr.ht
      ./setup.py build
  - archive: |
      cd builds.sr.ht
      pkgver=$(git describe | sed -e 's/-/_/g')
      echo "pkgver=$pkgver" >> ~/.buildenv
      git archive -o ~/sr.ht-pkgbuilds/builds.sr.ht/builds.sr.ht-$pkgver.tar.xz \
        --prefix=builds.sr.ht-$pkgver/ HEAD
  - package: |
      cd sr.ht-pkgbuilds/builds.sr.ht
      pkgrel=$(pacman -Si builds.sr.ht | grep Version | cut -d'-' -f2)
      pkgrel=$(expr $pkgrel + 1)
      sed -e "s/pkgver=.*/pkgver=$pkgver/" -i PKGBUILD
      sed -e "s/pkgrel=.*/pkgrel=$pkgrel/" -i PKGBUILD
      echo "pkgrel=$pkgrel" >> ~/.buildenv
      updpkgsums
      makepkg --config ../makepkg.conf -s --noconfirm
      cd ~/builds.sr.ht
      git describe --exact-match HEAD || complete-build
  - deploy: |
      cd sr.ht-pkgbuilds/builds.sr.ht
      sshopts="-o StrictHostKeyChecking=no" # TODO: remove this when builds run on a tty
      rsync --rsh="ssh $sshopts" -rP *.pkg.tar.xz{,.sig} $repo_server:$repo_path/
      ssh $sshopts $repo_server repo-add -n -R \
        $repo_path/sr.ht.db.tar.gz \
        $repo_path/builds.sr.ht-$pkgver-$pkgrel-any.pkg.tar.xz
      ssh $sshopts $repo_server repo-add -n -R \
        $repo_path/sr.ht.db.tar.gz \
        $repo_path/builds.sr.ht-images-$pkgver-$pkgrel-any.pkg.tar.xz
      ssh $sshopts $master sudo /usr/local/bin/update-srht builds.sr.ht
      for server in "${slaves[@]}"
      do
        ssh $sshopts $server sudo /usr/local/bin/update-srht builds.sr.ht builds.sr.ht-images
      done
