# To bootstrap, first manually build and deploy with this manifest using the previous version, then rebuild
image: openbsd/latest
packages:
  - qemu
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  arch: amd64
  release: "6.8"
  # genimg automatically generates a "bootstrap image" if building using a different version, but it
  # can also be forced.
  # openbsd_bootstrap: YES
  slaves:
    - deploy@azusa.runners.sr.ht
    - deploy@yui.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
triggers:
  - action: email
    condition: failure
    to: Drew DeVault <sir@cmpwn.com>
tasks:
  - genimg: |
      cd builds.sr.ht/images/openbsd/$release
      doas ./genimg $arch
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=256 ./images/control openbsd/$release sanity-check
  - deploy: |
      cd builds.sr.ht/images/openbsd/$release
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      for server in "${slaves[@]}"
      do
        ssh $server mkdir -p /var/lib/images/openbsd/$release/$arch
        openrsync $arch/root.img.qcow2 \
          ${server}:/var/lib/images/openbsd/$release/$arch/new_root.img.qcow2
        ssh $server mv /var/lib/images/openbsd/$release/$arch/new_root.img.qcow2 \
             /var/lib/images/openbsd/$release/$arch/root.img.qcow2
      done
