image: archlinux
repositories:
  sr.ht: https://mirror.sr.ht/sr.ht/archlinux/#1ED4E14494433AE3FD302CAB74B4BCCEA60D0437
packages:
  - qemu-headless
  - wget
  - libguestfs
  - procps-ng
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
tasks:
  - build: |
      cd builds.sr.ht
      cd images/archlinux
      sudo ./genimg
  - sanity-check: |
      cd builds.sr.ht
      ./images/control archlinux sanity-check
