image: archlinux
packages:
  - arch-install-scripts
  - qemu-headless
  - procps-ng
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  arch: x86_64
  slaves:
    - deploy@ritsu.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
triggers:
  - action: email
    condition: failure
    to: Drew DeVault <sir@cmpwn.com>
tasks:
  - genimg: |
      cd builds.sr.ht/images/archlinux
      sudo sed -e 's/IgnorePkg.*/#IgnorePkg/' -i /etc/pacman.conf
      sudo ./genimg
  - sanity-check: |
      cd builds.sr.ht
      if [ -e /dev/kvm ]
      then
          MEMORY=1024 ./images/control archlinux sanity-check
      else
          echo "KVM unavailable, skipping sanity check"
      fi
  - deploy: |
      cd builds.sr.ht/images/archlinux
      sshopts="-o StrictHostKeyChecking=no"
      for server in "${slaves[@]}"
      do
        rsync \
          --rsh="ssh $sshopts" \
          -rzP $arch/initrd $arch/kernel $arch/root.img.qcow2 \
          ${server}:/var/lib/images/archlinux/$arch-new
        ssh $sshopts $server \
          mv /var/lib/images/archlinux/$arch-new/{initrd,kernel,root.img.qcow2} \
             /var/lib/images/archlinux/$arch
        ssh $sshopts $server rm -rf /var/lib/images/archlinux/$arch-new
      done
