image: debian/sid
packages:
  - debootstrap
  - qemu-system-x86
  - libguestfs-tools
  - procps
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  slaves:
    - deploy@mio.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
tasks:
  - genimg: |
      cd builds.sr.ht
      cd images/debian/sid
      sudo ./genimg
  - sanity-check: |
      cd builds.sr.ht
      # Debian does not have a kvm group so we just gotta do it this way
      sudo chmod 666 /dev/kvm
      MEMORY=1024 ./images/control debian/sid sanity-check
  - deploy: |
      cd builds.sr.ht/images/debian/sid
      sshopts="-o StrictHostKeyChecking=no"
      for server in "${slaves[@]}"
      do
        rsync \
          --rsh="ssh $sshopts" \
          -rzP initrd kernel root.img.qcow2 \
          ${server}:/var/lib/images/debian/sid-new
        ssh $sshopts $server \
          mv /var/lib/images/debian/sid-new/{initrd,kernel,root.img.qcow2} \
             /var/lib/images/debian/sid/
        ssh $sshopts $server rm -rf /var/lib/images/debian/sid-new
      done
