image: debian/stretch
packages:
  - debootstrap
  - e2fsprogs
  - qemu-system-x86
  - rsync
  - extlinux # temporary
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  release: stretch
  slaves:
    - deploy@mio.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
tasks:
  - genimg: |
      cd builds.sr.ht
      cd images/debian/$release
      sudo ./genimg
  - sanity-check: |
      cd builds.sr.ht
      # Debian does not have a kvm group so we just gotta do it this way
      sudo chown build:build /dev/kvm
      MEMORY=1024 ./images/control debian/$release sanity-check
  - deploy: |
      cd builds.sr.ht/images/debian/$release
      sshopts="-o StrictHostKeyChecking=no"
      for server in "${slaves[@]}"
      do
        rsync \
          --rsh="ssh $sshopts" -rzP root.img.qcow2 \
          ${server}:/var/lib/images/debian/$release/new_root.img.qcow2
        ssh $sshopts $server \
          mv /var/lib/images/debian/$release/new_root.img.qcow2 \
             /var/lib/images/debian/$release/root.img.qcow2
      done
