image: debian/unstable
packages:
  - debootstrap
  - e2fsprogs
  - qemu-user-static
  - binfmt-support
  - rsync
  - extlinux
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  arch: ppc64el
  release: stable
  slaves:
    - deploy@azusa.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
triggers:
  - action: email
    condition: failure
    to: Drew DeVault <sir@cmpwn.com>
tasks:
  - genimg: |
      cd builds.sr.ht
      cd images/debian/$release
      case "$arch" in
          arm64)
              qpkg=arm
              ;;
          amd64)
              qpkg=x86
              ;;
          ppc64el)
              qpkg=ppc
              ;;
      esac
      sudo apt install -y qemu-system-"$qpkg"
      sudo ./genimg $arch
  - sanity-check: |
      cd builds.sr.ht
      if [ -e /dev/kvm ] && [ "$(uname -m)" = "x86_64" ] && [ "$arch" = "amd64" ]
      then
          # Debian does not have a kvm group so we just gotta do it this way
          sudo chown build:build /dev/kvm
          MEMORY=1024 ./images/control debian/$release sanity-check
      else
          echo "KVM unavailable, skipping sanity check"
      fi
  - deploy: |
      cd builds.sr.ht/images/debian/$release
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      for server in "${slaves[@]}"
      do
        ssh $server mkdir -p /var/lib/images/debian/$release/$arch
        rsync -rzP $arch/root.img.qcow2 \
          ${server}:/var/lib/images/debian/$release/$arch/new_root.img.qcow2
        case "$arch" in
            arm64)
                rsync -rzP $arch/vmlinuz \
                  ${server}:/var/lib/images/debian/$release/$arch/vmlinuz.new
                rsync -rzP $arch/initrd.img \
                  ${server}:/var/lib/images/debian/$release/$arch/initrd.img.new
                ;;
        esac
        ssh $server \
          mv /var/lib/images/debian/$release/$arch/new_root.img.qcow2 \
             /var/lib/images/debian/$release/$arch/root.img.qcow2
        case "$arch" in
            arm64)
                ssh $server \
                  mv /var/lib/images/debian/$release/$arch/vmlinuz.new \
                     /var/lib/images/debian/$release/$arch/vmlinuz
                ssh $server \
                  mv /var/lib/images/debian/$release/$arch/initrd.img.new \
                     /var/lib/images/debian/$release/$arch/initrd.img
                ;;
        esac
      done
