image: freebsd/latest
packages:
  - qemu
  - qemu-utils
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  arch: amd64
  release: "12.x"
  slaves:
    - deploy@mio.runners.sr.ht
    - deploy@yui.runners.sr.ht
    - deploy@azusa.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
triggers:
  - action: email
    condition: failure
    to: Drew DeVault <sir@cmpwn.com>
tasks:
  - genimg: |
      cd builds.sr.ht/images/freebsd/$release
      sudo ./genimg $arch
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=1024 ./images/control freebsd/$release sanity-check
  - deploy: |
      cd builds.sr.ht/images/freebsd/$release
      echo "StrictHostKeyChecking=no" >> ~/.ssh/config
      for server in "${slaves[@]}"
      do
        ssh $server mkdir -p /var/lib/images/freebsd/$release/$arch
        rsync -rzP $arch/root.img.qcow2 \
          ${server}:/var/lib/images/freebsd/$release/$arch/new_root.img.qcow2
        ssh $server \
          mv /var/lib/images/freebsd/$release/$arch/new_root.img.qcow2 \
             /var/lib/images/freebsd/$release/$arch/root.img.qcow2
      done
