image: alpine
packages:
  - rsync
  - qemu-img
  - qemu-system-x86_64
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
tasks:
  - genimg: |
      cd builds.sr.ht/images/alpine
      sudo ./genimg
      # World was corrupted during genimg
      # TODO: Avoid that <_<
      sudo apk add qemu-system-x86_64
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=1024 ./images/control alpine sanity-check
# TODO: deploy
