image: alpine
packages:
  - qemu-system-x86_64
  - qemu-img
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
tasks:
  - genimg: |
      cd builds.sr.ht
      cd images/alpine
      sudo cp pacman.conf /etc
      sudo ./genimg
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=1024 ./images/control alpine sanity-check
# TODO: deploy
