image: alpine/edge
arch: x86_64
packages:
  - e2fsprogs
  - qemu-img
  - qemu-system-x86_64
  - rsync
  - sfdisk
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  release: unstable
  slaves:
    - deploy@mio.runners.sr.ht
    - deploy@yui.runners.sr.ht
tasks:
  - genimg: |
      cd builds.sr.ht/images/nixos
      ./genimg "${release}" "$(uname -m)"
  - kvm: |
      sudo modprobe kvm-intel
      sleep 1
      sudo chown build:build /dev/kvm
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=1024 ./images/control "nixos/${release}" sanity-check
  - deploy: |
      cd builds.sr.ht/images/alpine/$release
      sshopts="-o StrictHostKeyChecking=no"
      for server in "${slaves[@]}"
      do
        rsync \
          --rsh="ssh $sshopts" -rzP $arch/root.img.qcow2 \
          ${server}:/var/lib/images/nixos/$release/$arch/new_root.img.qcow2
        ssh $sshopts $server \
          mv /var/lib/images/nixos/$release/$arch/new_root.img.qcow2 \
             /var/lib/images/nixos/$release/$arch/root.img.qcow2
      done
