image: alpine/edge
arch: x86_64
packages:
  - e2fsprogs
  - qemu-img
  - qemu-system-x86_64
  - rsync
  - sfdisk
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  release: unstable
tasks:
  - genimg: |
      cd builds.sr.ht/images/nixos
      ./genimg "${release}" "$(uname -m)"
  - kvm: |
      sudo modprobe kvm-intel
      sleep 1
      sudo chown build:build /dev/kvm
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=1024 ./images/control "nixos/${release}" sanity-check

