image: alpine/edge
arch: x86_64
packages:
  - e2fsprogs
  - qemu-img
  - qemu-system-x86_64
  - rsync
  - sfdisk
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  # Can be: "unstable" or "xx.yy" (stable releases such as 18.09)
  release: unstable
  # Remember to change the builder arch too, since genimg builds an image with
  # the same arch as the host
  arch: x86_64 # can be: x86_64 or aarch64
tasks:
  - genimg: |
      cd builds.sr.ht/images/nixos
      ./genimg "${release}" "${arch}"
  - kvm: |
      sudo modprobe kvm-intel
      sleep 1
      sudo chown build:build /dev/kvm
  - sanity-check: |
      cd builds.sr.ht
      MEMORY=1024 ./images/control "nixos/${release}" sanity-check

