image: fedora/29
packages:
  - e2fsprogs
  - qemu-system-x86
  - qemu-img
  - rsync
sources:
  - https://git.sr.ht/~sircmpwn/builds.sr.ht
environment:
  arch: x86_64
  release: "29"
  slaves:
    - deploy@mio.runners.sr.ht
    - deploy@yui.runners.sr.ht
    - deploy@azusa.runners.sr.ht
secrets:
  - fa00a8d3-7b63-42d5-8060-3bb31c3e3018
triggers:
  - action: email
    condition: failure
    to: Drew DeVault <sir@cmpwn.com>
tasks:
  - genimg: |
      cd builds.sr.ht
      cd images/fedora/$release
      sudo ./genimg $arch
  - sanity-check: |
      cd builds.sr.ht
      sudo chown build:build /dev/kvm
      MEMORY=1024 ./images/control fedora/$release sanity-check
  - deploy: |
      cd builds.sr.ht/images/fedora/$release
      sshopts="-o StrictHostKeyChecking=no"
      for server in "${slaves[@]}"
      do
        rsync \
          --rsh="ssh $sshopts" -rzP $arch/root.img.qcow2 \
          ${server}:/var/lib/images/fedora/$release/$arch/new_root.img.qcow2
        ssh $sshopts $server \
          mv /var/lib/images/fedora/$release/$arch/new_root.img.qcow2 \
             /var/lib/images/fedora/$release/$arch/root.img.qcow2
      done
